site_name: machwave
site_url: https://felipebogaertsm.github.io/machwave/
site_description: Chemical propulsion simulator - solid, liquid and hybrid motors
site_author: Felipe Bogaerts de Mattos

repo_url: https://github.com/felipebogaertsm/machwave
repo_name: felipebogaertsm/machwave

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            docstring_style: google

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Rocket Theory:
      - 1. Nozzle Theory: theory/nozzle.md
      - 2. Balance of Mass: theory/mass_balance.md
      - 3. Thrust and Performance: theory/performance.md
      - 4. Nozzle Losses: theory/nozzle_losses.md
  - Modules:
      - adapters:
          - Overview: api/adapters.md
          - rocketpy: api/adapters/rocketpy.md
      - common: api/common.md
      - core:
          - Overview: api/core.md
          - compressible_flow: api/core/compressible_flow.md
          - mass_balance: api/core/mass_balance.md
          - solvers: api/core/solvers.md
          - structural: api/core/structural.md
      - io: api/io.md
      - models:
          - Overview: api/models.md
          - feed_systems:
              - Overview: api/models/feed_systems.md
              - tanks: api/models/feed_systems/tanks.md
          - grain:
              - Overview: api/models/grain.md
              - fmm: api/models/grain/fmm.md
              - geometries: api/models/grain/geometries.md
          - motors: api/models/motors.md
          - propellants:
              - Overview: api/models/propellants.md
              - categories: api/models/propellants/categories.md
              - formulations: api/models/propellants/formulations.md
          - thrust_chamber: api/models/thrust_chamber.md
      - montecarlo: api/montecarlo.md
      - services:
          - Overview: api/services.md
          - plots: api/services/plots.md
      - simulation: api/simulation.md
      - states: api/states.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
