site_name: machwave
site_url: https://felipebogaertsm.github.io/machwave/
site_description: Chemical propulsion simulator - solid, liquid and hybrid motors
site_author: Felipe Bogaerts de Mattos

repo_url: https://github.com/felipebogaertsm/machwave
repo_name: felipebogaertsm/machwave

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            docstring_style: google

nav:
  - Home: index.md
  - Modules:
      - adapters:
          - Overview: api/adapters.md
          - rocketpy: api/adapters/rocketpy.md
      - common: api/common.md
      - core:
          - Overview: api/core.md
          - compressible_flow: api/core/compressible_flow.md
          - equations: api/core/equations.md
          - solvers: api/core/solvers.md
          - structural: api/core/structural.md
      - io: api/io.md
      - models:
          - Overview: api/models.md
          - feed_systems:
              - Overview: api/models/feed_systems.md
              - tanks: api/models/feed_systems/tanks.md
          - grain:
              - Overview: api/models/grain.md
              - fmm: api/models/grain/fmm.md
              - geometries: api/models/grain/geometries.md
          - motors: api/models/motors.md
          - propellants:
              - Overview: api/models/propellants.md
              - categories: api/models/propellants/categories.md
              - formulations: api/models/propellants/formulations.md
          - thrust_chamber: api/models/thrust_chamber.md
      - montecarlo: api/montecarlo.md
      - services:
          - Overview: api/services.md
          - plots: api/services/plots.md
      - simulations: api/simulations.md
      - states:
          - Overview: api/states.md
          - internal_ballistics: api/states/internal_ballistics.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
