# Generated by Django 3.1.7 on 2021-09-05 23:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatesWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('n', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('od_grain', models.FloatField()),
                ('id_grain', models.FloatField()),
                ('l_grain', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotorWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('is_simulated', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm_solver.batesweb')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_0', models.FloatField(blank=True, default=0.0)),
                ('igniter_pressure', models.FloatField(blank=True, default=1.5)),
                ('rail_length', models.FloatField(blank=True, default=5)),
                ('safety_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('grain_spacing', models.FloatField(default=0.01)),
                ('casing_id', models.FloatField()),
                ('casing_od', models.FloatField()),
                ('liner_thickness', models.FloatField()),
                ('throat_diameter', models.FloatField()),
                ('divergent_angle', models.FloatField()),
                ('convergent_angle', models.FloatField()),
                ('expansion_ratio', models.FloatField()),
                ('casing_c_1', models.FloatField(default=0.00506)),
                ('casing_c_2', models.FloatField(default=0.0)),
                ('yield_casing', models.FloatField()),
                ('yield_bulkhead', models.FloatField()),
                ('yield_nozzle', models.FloatField()),
                ('screw_diameter', models.FloatField()),
                ('screw_clearance_diameter', models.FloatField()),
                ('screw_tensile_strength', models.FloatField()),
                ('max_screw_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_res', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000)])),
                ('dt', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1)])),
                ('ddt', models.FloatField(blank=True, default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='srm_solver.motorweb')),
                ('op_settings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='srm_solver.operationsettings')),
                ('sim_settings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='srm_solver.simulationsettings')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RocketWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mass_wo_motor', models.FloatField()),
                ('drag_coefficient', models.FloatField()),
                ('rocket_diameter', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('drogue_time', models.FloatField()),
                ('drogue_drag_coeff', models.FloatField()),
                ('drogue_diameter', models.FloatField()),
                ('main_activation_height', models.FloatField()),
                ('main_drag_coeff', models.FloatField()),
                ('main_diameter', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropellantWeb',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ce', models.FloatField()),
                ('pp', models.FloatField()),
                ('k_mix_ch', models.FloatField()),
                ('k_2ph_ex', models.FloatField()),
                ('t_0_ideal', models.FloatField()),
                ('m_ch', models.FloatField()),
                ('m_ex', models.FloatField()),
                ('i_sp_frozen', models.FloatField()),
                ('i_sp_shifting', models.FloatField()),
                ('qsi_ch', models.FloatField()),
                ('qsi_ex', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='motorweb',
            name='propellant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm_solver.propellantweb'),
        ),
        migrations.AddField(
            model_name='motorweb',
            name='recovery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm_solver.recoveryweb'),
        ),
        migrations.AddField(
            model_name='motorweb',
            name='rocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm_solver.rocketweb'),
        ),
        migrations.AddField(
            model_name='motorweb',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srm_solver.structureweb'),
        ),
        migrations.AddField(
            model_name='motorweb',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
