@startuml machwave.models.propulsion.grain
!pragma useIntermediatePackages false

class machwave.models.propulsion.grain.base.Grain {
  segments: list[GrainSegment]
}
class machwave.models.propulsion.grain.base.GrainGeometryError {
  message: str
}
abstract class machwave.models.propulsion.grain.base.GrainSegment {
  length: float
  outer_diameter: float
  spacing: float
  inhibited_ends: int
}
abstract class machwave.models.propulsion.grain.base.GrainSegment2D {
}
abstract class machwave.models.propulsion.grain.base.GrainSegment3D {
}
abstract class machwave.models.propulsion.grain.fmm.base.FMMGrainSegment {
  map_dim: int
  maps: None
  mask: None
  masked_face: None
  regression_map: None
}
abstract class machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D {
  face_area_interp_func: Optional[Callable[[float], float]]
}
abstract class machwave.models.propulsion.grain.fmm._3d.FMMGrainSegment3D {
}
class machwave.models.propulsion.grain.fmm.stl.FMMSTLGrainSegment {
  file_path: str
  outer_diameter: float
  length: float
  face_area_interp_func: None
}
class machwave.models.propulsion.grain.geometries.bates.BatesSegment {
  core_diameter: float
}
class machwave.models.propulsion.grain.geometries.conical.ConicalGrainSegment {
  upper_core_diameter: float
  lower_core_diameter: float
}
class machwave.models.propulsion.grain.geometries.d_grain.DGrainSegment {
  slot_offset: float
}
class machwave.models.propulsion.grain.geometries.multi_port.MultiPortGrainSegment {
  port_diameter: float
  port_radial_count: None
  port_level_count: None
}
class machwave.models.propulsion.grain.geometries.rod_and_tube.RodAndTubeGrainSegment {
  rod_outer_diameter: float
  tube_inner_diameter: float
}
class machwave.models.propulsion.grain.geometries.star.StarGrainSegment {
  number_of_points: None
  point_length: float
  point_width: float
}
class machwave.models.propulsion.grain.geometries.wagon_wheel.WagonWheelGrainSegment {
  core_diameter: float
  number_of_ports: None
  port_inner_diameter: float
  port_outer_diameter: float
  port_angular_width: float
}
machwave.models.propulsion.grain.base.Grain *-- machwave.models.propulsion.grain.base.GrainSegment
machwave.models.propulsion.grain.base.GrainSegment <|-- machwave.models.propulsion.grain.base.GrainSegment2D
machwave.models.propulsion.grain.base.GrainSegment <|-- machwave.models.propulsion.grain.base.GrainSegment3D
machwave.models.propulsion.grain.base.GrainSegment <|-- machwave.models.propulsion.grain.fmm.base.FMMGrainSegment
machwave.models.propulsion.grain.fmm.base.FMMGrainSegment <|-- machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D
machwave.models.propulsion.grain.base.GrainSegment2D <|-- machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D
machwave.models.propulsion.grain.fmm.base.FMMGrainSegment <|-- machwave.models.propulsion.grain.fmm._3d.FMMGrainSegment3D
machwave.models.propulsion.grain.base.GrainSegment3D <|-- machwave.models.propulsion.grain.fmm._3d.FMMGrainSegment3D
machwave.models.propulsion.grain.fmm._3d.FMMGrainSegment3D <|-- machwave.models.propulsion.grain.fmm.stl.FMMSTLGrainSegment
machwave.models.propulsion.grain.base.GrainSegment2D <|-- machwave.models.propulsion.grain.geometries.bates.BatesSegment
machwave.models.propulsion.grain.fmm._3d.FMMGrainSegment3D <|-- machwave.models.propulsion.grain.geometries.conical.ConicalGrainSegment
machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D <|-- machwave.models.propulsion.grain.geometries.d_grain.DGrainSegment
machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D <|-- machwave.models.propulsion.grain.geometries.multi_port.MultiPortGrainSegment
machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D <|-- machwave.models.propulsion.grain.geometries.rod_and_tube.RodAndTubeGrainSegment
machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D <|-- machwave.models.propulsion.grain.geometries.star.StarGrainSegment
machwave.models.propulsion.grain.fmm._2d.FMMGrainSegment2D <|-- machwave.models.propulsion.grain.geometries.wagon_wheel.WagonWheelGrainSegment
footer Generated by //py2puml//
@enduml

