@startuml machwave.simulations
!pragma useIntermediatePackages false

class machwave.simulations.ballistics.BallisticSimulation {
  params: BallisticSimulationParameters
  rocket: Rocket
  atmosphere: Atmosphere
  t: None
  ballistic_state: None
}
class machwave.simulations.ballistics.BallisticSimulationParameters {
  thrust: ndarray
  motor_dry_mass: float
  initial_propellant_mass: float
  time: ndarray
  d_t: float
  initial_elevation_amsl: float
  rail_length: float
}
class machwave.simulations.internal_ballistics.InternalBallistics {
  motor: Motor
  params: InternalBallisticsParams
  t: ndarray
  motor_state: MotorState | None
}
class machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupled {
  params: InternalBallisticsCoupledParams
  rocket: Rocket
  t: None
  motor_state: None
  ballistic_state: None
}
class machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupledParams {
  atmosphere: Atmosphere
  d_t: float
  dd_t: float
  initial_elevation_amsl: float
  igniter_pressure: float
  rail_length: float
}
class machwave.simulations.internal_ballistics.InternalBallisticsParams {
  d_t: float
  igniter_pressure: float
  external_pressure: float
}
abstract class machwave.simulations.base.Simulation {
  params: SimulationParameters
}
class machwave.simulations.base.SimulationParameters {
}
machwave.simulations.ballistics.BallisticSimulation *-- machwave.simulations.ballistics.BallisticSimulationParameters
machwave.simulations.base.Simulation <|-- machwave.simulations.ballistics.BallisticSimulation
machwave.simulations.base.SimulationParameters <|-- machwave.simulations.ballistics.BallisticSimulationParameters
machwave.simulations.internal_ballistics.InternalBallistics *-- machwave.simulations.internal_ballistics.InternalBallisticsParams
machwave.simulations.base.Simulation <|-- machwave.simulations.internal_ballistics.InternalBallistics
machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupled *-- machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupledParams
machwave.simulations.base.Simulation <|-- machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupled
machwave.simulations.base.SimulationParameters <|-- machwave.simulations.internal_balistics_coupled.InternalBallisticsCoupledParams
machwave.simulations.base.SimulationParameters <|-- machwave.simulations.internal_ballistics.InternalBallisticsParams
machwave.simulations.base.Simulation *-- machwave.simulations.base.SimulationParameters
footer Generated by //py2puml//
@enduml

