@startuml machwave.models.propulsion.thrust_chamber
!pragma useIntermediatePackages false

class machwave.models.propulsion.thrust_chamber.injector.BipropellantInjector {
  discharge_coefficient_fuel: float
  discharge_coefficient_oxidizer: float
  area_fuel: float
  area_ox: float
}
class machwave.models.propulsion.thrust_chamber.combustion_chamber.CombustionChamber {
  casing_inner_diameter: float
  casing_outer_diameter: float
  internal_length: float
  thermal_liner_thickness: float
}
class machwave.models.propulsion.thrust_chamber.base.LiquidEngineThrustChamber {
  injector: BipropellantInjector
}
class machwave.models.propulsion.thrust_chamber.nozzle.Nozzle {
  inlet_diameter: None
  throat_diameter: None
  divergent_angle: None
  convergent_angle: None
  expansion_ratio: None
  material: None
}
class machwave.models.propulsion.thrust_chamber.base.SolidMotorThrustChamber {
}
class machwave.models.propulsion.thrust_chamber.base.ThrustChamber {
  nozzle: Nozzle
  combustion_chamber: CombustionChamber
  dry_mass: float
}
machwave.models.propulsion.thrust_chamber.base.LiquidEngineThrustChamber *-- machwave.models.propulsion.thrust_chamber.injector.BipropellantInjector
machwave.models.propulsion.thrust_chamber.base.ThrustChamber <|-- machwave.models.propulsion.thrust_chamber.base.LiquidEngineThrustChamber
machwave.models.propulsion.thrust_chamber.base.ThrustChamber <|-- machwave.models.propulsion.thrust_chamber.base.SolidMotorThrustChamber
machwave.models.propulsion.thrust_chamber.base.ThrustChamber *-- machwave.models.propulsion.thrust_chamber.nozzle.Nozzle
machwave.models.propulsion.thrust_chamber.base.ThrustChamber *-- machwave.models.propulsion.thrust_chamber.combustion_chamber.CombustionChamber
footer Generated by //py2puml//
@enduml

