# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\felip\Dropbox\Python\SRM-Solver\UI\SRM Solver.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


import numpy as np

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_Run = QtWidgets.QPushButton(self.centralwidget)
        self.button_Run.setGeometry(QtCore.QRect(930, 440, 61, 28))
        self.button_Run.setObjectName("button_Run")
        self.button_Plots = QtWidgets.QPushButton(self.centralwidget)
        self.button_Plots.setGeometry(QtCore.QRect(860, 440, 61, 28))
        self.button_Plots.setObjectName("button_Plots")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 110, 681, 336))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_Inputs_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_Inputs_2.setContentsMargins(0, 0, 0, 0)
        self.grid_Inputs_2.setObjectName("grid_Inputs_2")
        self.label_Div_angle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Div_angle.setObjectName("label_Div_angle")
        self.grid_Inputs_2.addWidget(self.label_Div_angle, 4, 2, 1, 1)
        self.label_Y_bulkhead = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Y_bulkhead.setObjectName("label_Y_bulkhead")
        self.grid_Inputs_2.addWidget(self.label_Y_bulkhead, 9, 2, 1, 1)
        self.label_N = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_N.setObjectName("label_N")
        self.grid_Inputs_2.addWidget(self.label_N, 1, 0, 1, 1)
        self.line_D_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_D_in.setObjectName("line_D_in")
        self.grid_Inputs_2.addWidget(self.line_D_in, 1, 3, 1, 1)
        self.label_D_i = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D_i.setObjectName("label_D_i")
        self.grid_Inputs_2.addWidget(self.label_D_i, 1, 2, 1, 1)
        self.line_Conv_angle = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Conv_angle.setObjectName("line_Conv_angle")
        self.grid_Inputs_2.addWidget(self.line_Conv_angle, 5, 3, 1, 1)
        self.line_Nozzle_mat = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Nozzle_mat.setObjectName("line_Nozzle_mat")
        self.grid_Inputs_2.addWidget(self.line_Nozzle_mat, 6, 3, 1, 1)
        self.line_m_motor = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_m_motor.setObjectName("line_m_motor")
        self.grid_Inputs_2.addWidget(self.line_m_motor, 10, 3, 1, 1)
        self.line_D_throat = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_D_throat.setObjectName("line_D_throat")
        self.grid_Inputs_2.addWidget(self.line_D_throat, 3, 3, 1, 1)
        self.line_grain_spacing = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_grain_spacing.setObjectName("line_grain_spacing")
        self.grid_Inputs_2.addWidget(self.line_grain_spacing, 5, 1, 1, 1)
        self.line_Y_bulkhead = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Y_bulkhead.setObjectName("line_Y_bulkhead")
        self.grid_Inputs_2.addWidget(self.line_Y_bulkhead, 9, 3, 1, 1)
        self.line_D_core = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_D_core.setObjectName("line_D_core")
        self.grid_Inputs_2.addWidget(self.line_D_core, 4, 1, 1, 1)
        self.label_L_grain = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_L_grain.setObjectName("label_L_grain")
        self.grid_Inputs_2.addWidget(self.label_L_grain, 3, 0, 1, 1)
        self.label_Conv_angle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Conv_angle.setObjectName("label_Conv_angle")
        self.grid_Inputs_2.addWidget(self.label_Conv_angle, 5, 2, 1, 1)
        self.label_D_grain = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D_grain.setObjectName("label_D_grain")
        self.grid_Inputs_2.addWidget(self.label_D_grain, 2, 0, 1, 1)
        self.line_Y_nozzle = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Y_nozzle.setObjectName("line_Y_nozzle")
        self.grid_Inputs_2.addWidget(self.line_Y_nozzle, 8, 3, 1, 1)
        self.label_m_motor = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_m_motor.setObjectName("label_m_motor")
        self.grid_Inputs_2.addWidget(self.label_m_motor, 10, 2, 1, 1)
        self.label_Y_nozzle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Y_nozzle.setObjectName("label_Y_nozzle")
        self.grid_Inputs_2.addWidget(self.label_Y_nozzle, 8, 2, 1, 1)
        self.label_Y_cc = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Y_cc.setObjectName("label_Y_cc")
        self.grid_Inputs_2.addWidget(self.label_Y_cc, 7, 2, 1, 1)
        self.label_D_core = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D_core.setObjectName("label_D_core")
        self.grid_Inputs_2.addWidget(self.label_D_core, 4, 0, 1, 1)
        self.line_Div_angle = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Div_angle.setObjectName("line_Div_angle")
        self.grid_Inputs_2.addWidget(self.line_Div_angle, 4, 3, 1, 1)
        self.line_D_grain = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_D_grain.setObjectName("line_D_grain")
        self.grid_Inputs_2.addWidget(self.line_D_grain, 2, 1, 1, 1)
        self.label_grain_spacing = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_grain_spacing.setObjectName("label_grain_spacing")
        self.grid_Inputs_2.addWidget(self.label_grain_spacing, 5, 0, 1, 1)
        self.line_N = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_N.setObjectName("line_N")
        self.grid_Inputs_2.addWidget(self.line_N, 1, 1, 1, 1)
        self.label_Nozzle_mat = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Nozzle_mat.setObjectName("label_Nozzle_mat")
        self.grid_Inputs_2.addWidget(self.label_Nozzle_mat, 6, 2, 1, 1)
        self.line_Y_cc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Y_cc.setObjectName("line_Y_cc")
        self.grid_Inputs_2.addWidget(self.line_Y_cc, 7, 3, 1, 1)
        self.label_D_o = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D_o.setObjectName("label_D_o")
        self.grid_Inputs_2.addWidget(self.label_D_o, 2, 2, 1, 1)
        self.line_L_grain = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_L_grain.setObjectName("line_L_grain")
        self.grid_Inputs_2.addWidget(self.line_L_grain, 3, 1, 1, 1)
        self.label_D_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D_t.setObjectName("label_D_t")
        self.grid_Inputs_2.addWidget(self.label_D_t, 3, 2, 1, 1)
        self.line_D_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_D_out.setObjectName("line_D_out")
        self.grid_Inputs_2.addWidget(self.line_D_out, 2, 3, 1, 1)
        self.label_sf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_sf.setObjectName("label_sf")
        self.grid_Inputs_2.addWidget(self.label_sf, 0, 2, 1, 1)
        self.line_sf = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_sf.setObjectName("line_sf")
        self.grid_Inputs_2.addWidget(self.line_sf, 0, 3, 1, 1)
        self.label_propellant = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_propellant.setObjectName("label_propellant")
        self.grid_Inputs_2.addWidget(self.label_propellant, 0, 0, 1, 1)
        self.label_P_igniter = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_P_igniter.setObjectName("label_P_igniter")
        self.grid_Inputs_2.addWidget(self.label_P_igniter, 6, 0, 1, 1)
        self.line_P_igniter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_P_igniter.setObjectName("line_P_igniter")
        self.grid_Inputs_2.addWidget(self.line_P_igniter, 6, 1, 1, 1)
        self.label_P_external = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_P_external.setObjectName("label_P_external")
        self.grid_Inputs_2.addWidget(self.label_P_external, 7, 0, 1, 1)
        self.line_P_external = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_P_external.setObjectName("line_P_external")
        self.grid_Inputs_2.addWidget(self.line_P_external, 7, 1, 1, 1)
        self.combo_propellant = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_propellant.setObjectName("combo_propellant")
        self.combo_propellant.addItem("")
        self.combo_propellant.addItem("")
        self.combo_propellant.addItem("")
        self.combo_propellant.addItem("")
        self.combo_propellant.addItem("")
        self.grid_Inputs_2.addWidget(self.combo_propellant, 0, 1, 1, 1)
        self.label_Inputs = QtWidgets.QLabel(self.centralwidget)
        self.label_Inputs.setGeometry(QtCore.QRect(10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Inputs.setFont(font)
        self.label_Inputs.setObjectName("label_Inputs")
        self.label_Outputs = QtWidgets.QLabel(self.centralwidget)
        self.label_Outputs.setGeometry(QtCore.QRect(10, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Outputs.setFont(font)
        self.label_Outputs.setObjectName("label_Outputs")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 681, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_Inputs_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_Inputs_1.setContentsMargins(0, 0, 0, 0)
        self.grid_Inputs_1.setObjectName("grid_Inputs_1")
        self.label_motor_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_motor_name.setObjectName("label_motor_name")
        self.grid_Inputs_1.addWidget(self.label_motor_name, 0, 0, 1, 1)
        self.label_motor_manuf = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_motor_manuf.setObjectName("label_motor_manuf")
        self.grid_Inputs_1.addWidget(self.label_motor_manuf, 0, 2, 1, 1)
        self.line_motor_name = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_motor_name.setObjectName("line_motor_name")
        self.grid_Inputs_1.addWidget(self.line_motor_name, 0, 1, 1, 1)
        self.line_motor_manuf = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_motor_manuf.setObjectName("line_motor_manuf")
        self.grid_Inputs_1.addWidget(self.line_motor_manuf, 0, 3, 1, 1)
        self.label_IB_in = QtWidgets.QLabel(self.centralwidget)
        self.label_IB_in.setGeometry(QtCore.QRect(10, 80, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_IB_in.setFont(font)
        self.label_IB_in.setObjectName("label_IB_in")
        self.label_Structural = QtWidgets.QLabel(self.centralwidget)
        self.label_Structural.setGeometry(QtCore.QRect(370, 80, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Structural.setFont(font)
        self.label_Structural.setObjectName("label_Structural")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 510, 981, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_Outputs = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_Outputs.setContentsMargins(0, 0, 0, 0)
        self.grid_Outputs.setObjectName("grid_Outputs")
        self.label_Conv_thickness = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Conv_thickness.setObjectName("label_Conv_thickness")
        self.grid_Outputs.addWidget(self.label_Conv_thickness, 5, 2, 1, 1)
        self.label_Vol_efficiency = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Vol_efficiency.setObjectName("label_Vol_efficiency")
        self.grid_Outputs.addWidget(self.label_Vol_efficiency, 3, 0, 1, 1)
        self.label_casinf_sf = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_casinf_sf.setObjectName("label_casinf_sf")
        self.grid_Outputs.addWidget(self.label_casinf_sf, 3, 2, 1, 1)
        self.label_port_to_throat = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_port_to_throat.setObjectName("label_port_to_throat")
        self.grid_Outputs.addWidget(self.label_port_to_throat, 5, 0, 1, 1)
        self.label_m_prop = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_m_prop.setObjectName("label_m_prop")
        self.grid_Outputs.addWidget(self.label_m_prop, 0, 0, 1, 1)
        self.label_nozzle_exit_diameter = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_nozzle_exit_diameter.setObjectName("label_nozzle_exit_diameter")
        self.grid_Outputs.addWidget(self.label_nozzle_exit_diameter, 1, 2, 1, 1)
        self.label_burn_profile = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_burn_profile.setObjectName("label_burn_profile")
        self.grid_Outputs.addWidget(self.label_burn_profile, 1, 0, 1, 1)
        self.label_initial_to_final_Kn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_initial_to_final_Kn.setObjectName("label_initial_to_final_Kn")
        self.grid_Outputs.addWidget(self.label_initial_to_final_Kn, 2, 0, 1, 1)
        self.label_avg_nozzle_efficiency = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_avg_nozzle_efficiency.setObjectName("label_avg_nozzle_efficiency")
        self.grid_Outputs.addWidget(self.label_avg_nozzle_efficiency, 2, 2, 1, 1)
        self.label_avg_opt_exp_ratio = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_avg_opt_exp_ratio.setObjectName("label_avg_opt_exp_ratio")
        self.grid_Outputs.addWidget(self.label_avg_opt_exp_ratio, 0, 2, 1, 1)
        self.label_LD_ratio = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_LD_ratio.setObjectName("label_LD_ratio")
        self.grid_Outputs.addWidget(self.label_LD_ratio, 4, 0, 1, 1)
        self.label_t_thrust = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_t_thrust.setObjectName("label_t_thrust")
        self.grid_Outputs.addWidget(self.label_t_thrust, 5, 1, 1, 1)
        self.label_mean_pressure = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_mean_pressure.setObjectName("label_mean_pressure")
        self.grid_Outputs.addWidget(self.label_mean_pressure, 0, 1, 1, 1)
        self.label_max_pressure = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_max_pressure.setObjectName("label_max_pressure")
        self.grid_Outputs.addWidget(self.label_max_pressure, 1, 1, 1, 1)
        self.label_F_max = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_F_max.setObjectName("label_F_max")
        self.grid_Outputs.addWidget(self.label_F_max, 3, 1, 1, 1)
        self.label_I_total = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_I_total.setObjectName("label_I_total")
        self.grid_Outputs.addWidget(self.label_I_total, 2, 1, 1, 1)
        self.label_F_avh = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_F_avh.setObjectName("label_F_avh")
        self.grid_Outputs.addWidget(self.label_F_avh, 4, 1, 1, 1)
        self.label_t_burn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_t_burn.setObjectName("label_t_burn")
        self.grid_Outputs.addWidget(self.label_t_burn, 6, 1, 1, 1)
        self.label_bulkhead_thickness = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_bulkhead_thickness.setObjectName("label_bulkhead_thickness")
        self.grid_Outputs.addWidget(self.label_bulkhead_thickness, 4, 2, 1, 1)
        self.label_Div_thickness = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Div_thickness.setObjectName("label_Div_thickness")
        self.grid_Outputs.addWidget(self.label_Div_thickness, 6, 2, 1, 1)
        self.label_IB_out = QtWidgets.QLabel(self.centralwidget)
        self.label_IB_out.setGeometry(QtCore.QRect(10, 480, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_IB_out.setFont(font)
        self.label_IB_out.setObjectName("label_IB_out")
        self.label_P_and_Thrust = QtWidgets.QLabel(self.centralwidget)
        self.label_P_and_Thrust.setGeometry(QtCore.QRect(340, 480, 181, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_P_and_Thrust.setFont(font)
        self.label_P_and_Thrust.setObjectName("label_P_and_Thrust")
        self.label_Nozzle_Structural = QtWidgets.QLabel(self.centralwidget)
        self.label_Nozzle_Structural.setGeometry(QtCore.QRect(670, 480, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Nozzle_Structural.setFont(font)
        self.label_Nozzle_Structural.setObjectName("label_Nozzle_Structural")
        self.widget_grain = QtWidgets.QWidget(self.centralwidget)
        self.widget_grain.setGeometry(QtCore.QRect(700, 10, 291, 421))
        self.widget_grain.setObjectName("widget_grain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.action_Export_to_eng = QtWidgets.QAction(MainWindow)
        self.action_Export_to_eng.setObjectName("action_Export_to_eng")
        self.action_Export_to_csv = QtWidgets.QAction(MainWindow)
        self.action_Export_to_csv.setObjectName("action_Export_to_csv")
        self.action_Version_1_0 = QtWidgets.QAction(MainWindow)
        self.action_Version_1_0.setObjectName("action_Version_1_0")
        self.menuAbout.addAction(self.action_Version_1_0)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_Run.clicked.connect(run)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRM Solver"))
        self.button_Run.setText(_translate("MainWindow", "Run"))
        self.button_Plots.setText(_translate("MainWindow", "Plots"))
        self.label_Div_angle.setText(_translate("MainWindow", "Divergent Angle [deg]"))
        self.label_Y_bulkhead.setText(_translate("MainWindow", "Bulkhead Yield Strength [MPa]"))
        self.label_N.setText(_translate("MainWindow", "BATES Grain Count"))
        self.label_D_i.setText(_translate("MainWindow", "Chamber Inside Diameter [mm]"))
        self.label_L_grain.setText(_translate("MainWindow", "Grain Length (comma separated) [mm]"))
        self.label_Conv_angle.setText(_translate("MainWindow", "Convergent Angle [deg]"))
        self.label_D_grain.setText(_translate("MainWindow", "External Grain Diameter [mm]"))
        self.label_m_motor.setText(_translate("MainWindow", "Structural Mass [kg]"))
        self.label_Y_nozzle.setText(_translate("MainWindow", "Nozzle Yield Strength [MPa]"))
        self.label_Y_cc.setText(_translate("MainWindow", "Chamber Yield Strength [MPa]"))
        self.label_D_core.setText(_translate("MainWindow", "Grain Core (comma separated) [mm]"))
        self.label_grain_spacing.setText(_translate("MainWindow", "Grain Spacing [mm]"))
        self.label_Nozzle_mat.setText(_translate("MainWindow", "Steel Nozzle"))
        self.label_D_o.setText(_translate("MainWindow", "Chamber Outside Diameter [mm]"))
        self.label_D_t.setText(_translate("MainWindow", "Throat Diameter [mm]"))
        self.label_sf.setText(_translate("MainWindow", "Safety Factor"))
        self.label_propellant.setText(_translate("MainWindow", "Propellant"))
        self.label_P_igniter.setText(_translate("MainWindow", "Igniter Pressure [MPa]"))
        self.label_P_external.setText(_translate("MainWindow", "External Pressure [MPa]"))
        self.combo_propellant.setItemText(0, _translate("MainWindow", "KNSB Nakka"))
        self.combo_propellant.setItemText(1, _translate("MainWindow", "KNSB Gudnason"))
        self.combo_propellant.setItemText(2, _translate("MainWindow", "KNDX Nakka"))
        self.combo_propellant.setItemText(3, _translate("MainWindow", "KNSU Nakka"))
        self.combo_propellant.setItemText(4, _translate("MainWindow", "KNER Gudnason"))
        self.label_Inputs.setText(_translate("MainWindow", "Inputs"))
        self.label_Outputs.setText(_translate("MainWindow", "Outputs"))
        self.label_motor_name.setText(_translate("MainWindow", "Motor Name"))
        self.label_motor_manuf.setText(_translate("MainWindow", "Motor Manufacturer"))
        self.label_IB_in.setText(_translate("MainWindow", "Internal Ballistics"))
        self.label_Structural.setText(_translate("MainWindow", "Structural"))
        self.label_Conv_thickness.setText(_translate("MainWindow", "Convergent Nozzle Thickness [mm]"))
        self.label_Vol_efficiency.setText(_translate("MainWindow", "Volumetric Efficiency"))
        self.label_casinf_sf.setText(_translate("MainWindow", "Casing Safety Factor"))
        self.label_port_to_throat.setText(_translate("MainWindow", "Port to Throat ratio"))
        self.label_m_prop.setText(_translate("MainWindow", "Propellant Mass [kg]"))
        self.label_nozzle_exit_diameter.setText(_translate("MainWindow", "Exit Diameter [mm]"))
        self.label_burn_profile.setText(_translate("MainWindow", "Burn Profile"))
        self.label_initial_to_final_Kn.setText(_translate("MainWindow", "Initial to Final Kn ratio"))
        self.label_avg_nozzle_efficiency.setText(_translate("MainWindow", "Avg. Nozzle Efficiency"))
        self.label_avg_opt_exp_ratio.setText(_translate("MainWindow", "Avg. opt. exp. ratio"))
        self.label_LD_ratio.setText(_translate("MainWindow", "L/D ratio"))
        self.label_t_thrust.setText(_translate("MainWindow", "Thrust Time [s]"))
        self.label_mean_pressure.setText(_translate("MainWindow", "Mean Pressure [MPa]"))
        self.label_max_pressure.setText(_translate("MainWindow", "Max Pressure [MPa]"))
        self.label_F_max.setText(_translate("MainWindow", "Max Thrust [N]"))
        self.label_I_total.setText(_translate("MainWindow", "Total Impulse [N-s]"))
        self.label_F_avh.setText(_translate("MainWindow", "Mean Thrust [N]"))
        self.label_t_burn.setText(_translate("MainWindow", "Burn Time [s]"))
        self.label_bulkhead_thickness.setText(_translate("MainWindow", "Bulkhead Thickness"))
        self.label_Div_thickness.setText(_translate("MainWindow", "Divergent Nozzle Thickness [mm]"))
        self.label_IB_out.setText(_translate("MainWindow", "Internal Ballistics"))
        self.label_P_and_Thrust.setText(_translate("MainWindow", "Pressure and Thrust"))
        self.label_Nozzle_Structural.setText(_translate("MainWindow", "Nozzle Design and Structural"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.action_Export_to_eng.setText(_translate("MainWindow", "Export to .eng"))
        self.action_Export_to_csv.setText(_translate("MainWindow", "Export to .csv"))
        self.action_Version_1_0.setText(_translate("MainWindow", "Version 1.0"))

    def run(self):
        name, manuf = self.line_motor_name.text(), self.line_motor_manuf.text()
        m_motor = self.line_m_motor
        N, D_grain, grain_spacing = self.line_N, self.line_D_grain, self.line_grain_spacing
        D_core, L_grain = np.array([self.line_D_core]), np.array([self.line_L_grain])
        ce, pp, k_ch, k_ex, T0_ideal, M_ch, M_ex, Isp_frozen, Isp_shifting, \
        qsi_ch, qsi_ex = prop_data(self.line_propellant)
        print(name)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
