name: Publish Machwave to PyPI

on: 
  workflow_dispatch

jobs:
  publish_package:
    name: Publishing to PyPI
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH

      - name: Configure Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.MACHWAVE_PUBLISHING_TOKEN }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build the package
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          poetry publish --no-interaction
